version: '2.0'
services:
  mongodb:
    image: mongo:4.2.6-bionic
    container_name: ${CONTAINER_NAME}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

    volumes:
      - ./mongodb-volume:/data/db
    ports:
      - '${MONGO_PORT}:27017'
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge
